#lang racket
(define (square x)
  (* x x))
(define (compose f g)
  (lambda (x) (f (g x))))
(define (repeated f n)
  ((lambda () (if (> n 1) (compose f (repeated f (- n 1))) 
                  f))))
(define dx 0.00001)
(define (smooth f)
  (lambda (x) (/(+ (f (- x dx)) (f x) (f (+ x dx))) 3)))
((repeated (smooth square) 2) 5)
((smooth square) 5)
